# Generated by Django 5.2 on 2026-07-10 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_alertrule_create_maintenance_ticket_and_more'),
        ('events', '0001_initial'),
        ('maintenance', '0004_preventiveschedule_assigned_to_and_more'),
        ('teams', '0005_alter_invitation_role_alter_membership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('alert_triggered', 'Alert triggered'), ('alert_resolved', 'Alert resolved'), ('team_invitation', 'Team invitation'), ('maintenance_assignment', 'Maintenance assignment'), ('maintenance_resolution', 'Maintenance resolution'), ('support_request', 'Support request'), ('sales_inquiry', 'Sales inquiry'), ('test_email', 'Test email'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=40)),
                ('recipient', models.EmailField(db_index=True, max_length=254)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('bounced', 'Bounced'), ('complained', 'Complained'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('deferred', 'Deferred'), ('no_recipient', 'No recipient'), ('unknown', 'Unknown')], db_index=True, default='pending', max_length=30)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('last_event_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alerts.alert')),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.invitation')),
                ('maintenance_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.maintenanceticket')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_deliveries', to='teams.team')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Email deliveries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['team', 'notification_type', 'status'], name='events_emai_team_id_cbcb1a_idx'), models.Index(fields=['provider_message_id', 'recipient'], name='events_emai_provide_29ed5c_idx')],
            },
        ),
    ]
