# Generated by Django 5.2 on 2026-07-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_emaildelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildelivery',
            name='notification_type',
            field=models.CharField(choices=[('alert_triggered', 'Alert triggered'), ('alert_resolved', 'Alert resolved'), ('team_invitation', 'Team invitation'), ('maintenance_assignment', 'Maintenance assignment'), ('maintenance_resolution', 'Maintenance resolution'), ('support_request', 'Support request'), ('sales_inquiry', 'Sales inquiry'), ('impact_report', 'Business impact report'), ('test_email', 'Test email'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=40),
        ),
    ]
