# Generated by Django 5.2 on 2026-08-13 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dashboard_widget'),
        ('teams', '0008_team_remote_control_epoch_team_remote_control_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandCenterLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('personal', 'Personal'), ('team_default', 'Team default')], max_length=20)),
                ('layout', models.JSONField(default=dict)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_command_center_layouts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='command_center_layouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('scope', 'personal'), ('user__isnull', False)), models.Q(('scope', 'team_default'), ('user__isnull', True)), _connector='OR'), name='dashboard_layout_scope_user_valid'), models.UniqueConstraint(condition=models.Q(('scope', 'personal')), fields=('team', 'user'), name='dashboard_one_personal_layout'), models.UniqueConstraint(condition=models.Q(('scope', 'team_default')), fields=('team',), name='dashboard_one_team_default_layout')],
            },
        ),
    ]
