# Generated by Django 5.2 on 2026-04-09 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alerts", "0001_initial"),
        ("devices", "0001_initial"),
        ("teams", "0003_team_billing_details_last_changed_team_customer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="devices.device",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="teams.team",
                verbose_name="Team",
            ),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alert_rules",
                to="devices.device",
            ),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alert_rules",
                to="devices.site",
            ),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="teams.team",
                verbose_name="Team",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="alerts.alertrule",
            ),
        ),
    ]
