# Generated by Django 5.1.5 on 2026-04-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertrule",
            name="notify_whatsapp",
            field=models.BooleanField(
                default=False,
                help_text="Send out real-time alerts via WhatsApp. Requires a configured WhatsApp provider.",
            ),
        ),
    ]
