# Generated by Django 5.2 on 2026-06-18 06:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0003_alertrule_notify_whatsapp"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="alertrule",
            name="recipients",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific team members to notify.",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
