# Generated by Django 5.2 on 2026-06-19 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0004_alertrule_recipients"),
        ("maintenance", "0003_maintenanceticket_send_email_notification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertrule",
            name="create_maintenance_ticket",
            field=models.BooleanField(
                default=False,
                help_text="Automatically create a maintenance ticket when this alert triggers",
            ),
        ),
        migrations.AddField(
            model_name="alertrule",
            name="maintenance_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional checklist template to attach to the generated ticket",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="maintenance.tickettemplate",
            ),
        ),
    ]
