cli:
  app_directory: apps
  base_model: apps.teams.models.BaseTeamModel
  css_framework: tailwind
  module_path: apps
  template_directory: templates
  use_teams: true
default_context:
  _pegasus_version: 2025.5.1
  author_name: Shouheng
  bundler: vite
  ci: github_actions
  css_framework: tailwind
  css_theme: default
  database: postgres
  deploy_platform: none
  description: AI IOT platform
  docker_setup: default
  domain_name: localhost:8000
  email: tingshouheng@gmail.com
  enable_github_login: n
  enable_google_login: y
  enable_twitter_login: n
  front_end_framework: htmx
  github_username: tingsh
  include_static_files: n
  marketing_email_platform: none
  plugin_chat_mode: llm
  plugins:
  - chat
  post_process: y
  project_name: iiot
  project_slug: iot_platform
  python_package_manager: uv
  standalone_front_end: none
  stripe_payment_mode: checkout
  subscription_billing_model: default
  subscription_pricing_ui: stripe_hosted
  use_2fa: y
  use_admin_docs: n
  use_ai_rules_claude: n
  use_ai_rules_cursor: n
  use_api_auth: y
  use_api_keys: y
  use_async: y
  use_celery: y
  use_cloud_media_storage: y
  use_dark_mode: y
  use_debug_toolbar: y
  use_docker: y
  use_ecommerce_example: n
  use_examples: n
  use_flowbite: n
  use_health_checks: y
  use_impersonation: y
  use_sentry: y
  use_shadcn: n
  use_subscriptions: y
  use_teams: y
  use_teams_example: y
  use_translations: y
  use_wagtail: y
