# Generated by Django 5.1.5 on 2026-04-18 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0005_alter_device_connection_config_alter_device_port_and_more"),
        ("teams", "0005_alter_invitation_role_alter_membership_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Automation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "trigger_logic",
                    models.CharField(
                        choices=[
                            ("and", "All Conditions Match (AND)"),
                            ("or", "Any Condition Matches (OR)"),
                        ],
                        default="and",
                        max_length=10,
                    ),
                ),
                (
                    "cooldown_minutes",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Minutes to wait after execution before this automation can fire again",
                    ),
                ),
                ("last_triggered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teams.team",
                        verbose_name="Team",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AutomationAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("send_command", "Send Command to Device (RPC)"),
                            ("notify_email", "Send Email Notification"),
                            ("webhook", "Fire HTTP Webhook"),
                        ],
                        max_length=20,
                    ),
                ),
                ("command_key", models.CharField(blank=True, max_length=100)),
                (
                    "command_payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON wrapper for the command value",
                    ),
                ),
                (
                    "notify_emails",
                    models.CharField(
                        blank=True,
                        help_text="Comma separated list of email addresses",
                        max_length=255,
                    ),
                ),
                ("email_body", models.TextField(blank=True)),
                ("webhook_url", models.URLField(blank=True)),
                ("webhook_headers", models.JSONField(blank=True, default=dict)),
                (
                    "automation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="automations.automation",
                    ),
                ),
                (
                    "target_device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_actions",
                        to="devices.device",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teams.team",
                        verbose_name="Team",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AutomationCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("telemetry_key", models.CharField(max_length=100)),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("gt", "Greater Than (>)"),
                            ("lt", "Less Than (<)"),
                            ("gte", "Greater Than or Equal (>=)"),
                            ("lte", "Less Than or Equal (<=)"),
                            ("eq", "Equal (==)"),
                            ("neq", "Not Equal (!=)"),
                            ("is_true", "Is True"),
                            ("is_false", "Is False"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "threshold",
                    models.CharField(
                        blank=True,
                        help_text="Can be a number, string, or left blank for boolean checks.",
                        max_length=255,
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="How long the condition must remain true before acting (sustained trigger)",
                    ),
                ),
                (
                    "automation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="automations.automation",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_conditions",
                        to="devices.device",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teams.team",
                        verbose_name="Team",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AutomationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("partial", "Partial Success"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("details", models.TextField(blank=True)),
                (
                    "automation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="automations.automation",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teams.team",
                        verbose_name="Team",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
