# Generated by Django 5.2 on 2026-06-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="automationaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("send_command", "Send Command to Device (RPC)"),
                    ("notify_email", "Send Email Notification"),
                    ("webhook", "Fire HTTP Webhook"),
                    ("create_ticket", "Create Maintenance Ticket"),
                ],
                max_length=20,
            ),
        ),
    ]
