# Generated by Django 5.2 on 2026-06-10 04:08

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_setup_homepage"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketingStandardPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "social_image",
                    models.ImageField(
                        blank=True,
                        help_text="The image to use in social sharing metadata.",
                        null=True,
                        upload_to="",
                    ),
                ),
                ("hero_tagline", models.CharField(blank=True, max_length=255)),
                ("hero_title", models.CharField(blank=True, max_length=255)),
                ("hero_subtitle", models.TextField(blank=True)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("hero", 9),
                            ("trusted_by", 13),
                            ("feature_grid", 21),
                            ("feature_section", 29),
                            ("pricing_tiers", 39),
                            ("pricing_comparison", 43),
                            ("faq_accordion", 47),
                            ("solutions_section", 50),
                            ("final_cta", 56),
                            ("paragraph", 57),
                            ("html", 58),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "Industrial Intelligence",
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "Your Factory, Perfectly Synchronized.",
                                    "required": True,
                                },
                            ),
                            2: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Activate Cloud Access", "required": True},
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "/accounts/signup/", "required": True},
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Explore Platform", "required": False},
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "#features", "required": False},
                            ),
                            7: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("light", "Light Background"),
                                        ("dark", "Dark Background"),
                                    ]
                                },
                            ),
                            8: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {"default": True, "required": False},
                            ),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("tagline", 0),
                                        ("title", 1),
                                        ("subtitle", 2),
                                        ("primary_cta_text", 3),
                                        ("primary_cta_url", 4),
                                        ("secondary_cta_text", 5),
                                        ("secondary_cta_url", 6),
                                        ("bg_style", 7),
                                        ("show_terminal_simulator", 8),
                                    ]
                                ],
                                {},
                            ),
                            10: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "Empowering Industry Leaders Across ASEAN",
                                    "required": False,
                                },
                            ),
                            11: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Company Name"},
                            ),
                            12: ("wagtail.blocks.ListBlock", (11,), {}),
                            13: (
                                "wagtail.blocks.StructBlock",
                                [[("tagline", 10), ("companies", 12)]],
                                {},
                            ),
                            14: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Core Capabilities", "required": False},
                            ),
                            15: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "Engineered for Extreme Operational Resilience.",
                                    "required": True,
                                },
                            ),
                            16: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "fa-chart-line",
                                    "help_text": "FontAwesome class name",
                                    "required": True,
                                },
                            ),
                            17: ("wagtail.blocks.TextBlock", (), {"required": True}),
                            18: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            19: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("icon", 16),
                                        ("title", 2),
                                        ("description", 17),
                                        ("link_text", 18),
                                        ("link_url", 18),
                                    ]
                                ],
                                {},
                            ),
                            20: ("wagtail.blocks.ListBlock", (19,), {}),
                            21: (
                                "wagtail.blocks.StructBlock",
                                [[("tagline", 14), ("title", 15), ("features", 20)]],
                                {},
                            ),
                            22: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "fa-chart-line", "required": False},
                            ),
                            23: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Bullet Point"},
                            ),
                            24: (
                                "wagtail.blocks.ListBlock",
                                (23,),
                                {"required": False},
                            ),
                            25: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("dashboard", "Dashboard Mockup"),
                                        ("ai_chat", "AI Chat Mockup"),
                                        ("remote_control", "Remote Control Mockup"),
                                        ("multi_wan", "Multi-WAN Active Watchdog"),
                                    ]
                                },
                            ),
                            26: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Mockup", "required": False},
                            ),
                            27: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("left", "Image Left"),
                                        ("right", "Image Right"),
                                    ]
                                },
                            ),
                            28: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("white", "White"),
                                        ("light_gray", "Light Gray"),
                                        ("dark_indigo", "Dark Indigo"),
                                    ]
                                },
                            ),
                            29: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 2),
                                        ("description", 17),
                                        ("icon", 22),
                                        ("badge", 18),
                                        ("check_items", 24),
                                        ("mockup_type", 25),
                                        ("mockup_title", 26),
                                        ("align_image", 27),
                                        ("bg_color", 28),
                                    ]
                                ],
                                {},
                            ),
                            30: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Simple, fair pricing.", "required": False},
                            ),
                            31: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "No hidden device fees. No complex throughput math.",
                                    "required": False,
                                },
                            ),
                            32: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "/mo", "required": False},
                            ),
                            33: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Feature Item"},
                            ),
                            34: ("wagtail.blocks.ListBlock", (33,), {}),
                            35: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Get Started", "required": True},
                            ),
                            36: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {"default": False, "required": False},
                            ),
                            37: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("name", 2),
                                        ("badge", 18),
                                        ("price", 2),
                                        ("period", 32),
                                        ("features", 34),
                                        ("cta_text", 35),
                                        ("cta_url", 4),
                                        ("is_popular", 36),
                                    ]
                                ],
                                {},
                            ),
                            38: ("wagtail.blocks.ListBlock", (37,), {}),
                            39: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 30), ("subtitle", 31), ("tiers", 38)]],
                                {},
                            ),
                            40: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Compare Features", "required": False},
                            ),
                            41: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("name", 2),
                                        ("starter", 2),
                                        ("professional", 2),
                                        ("business", 2),
                                    ]
                                ],
                                {},
                            ),
                            42: ("wagtail.blocks.ListBlock", (41,), {}),
                            43: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 40), ("features", 42)]],
                                {},
                            ),
                            44: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "Frequently Asked Questions",
                                    "required": False,
                                },
                            ),
                            45: (
                                "wagtail.blocks.StructBlock",
                                [[("question", 2), ("answer", 17)]],
                                {},
                            ),
                            46: ("wagtail.blocks.ListBlock", (45,), {}),
                            47: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 44), ("faqs", 46)]],
                                {},
                            ),
                            48: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("grid", "Grids/Stats"),
                                        ("snowflake", "Snowflake Icon"),
                                        ("gear", "Rotating Gear"),
                                    ]
                                },
                            ),
                            49: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("white", "White"),
                                        ("light_gray", "Light Gray"),
                                    ]
                                },
                            ),
                            50: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("badge", 2),
                                        ("title", 2),
                                        ("pain_point_text", 17),
                                        ("solution_text", 17),
                                        ("illustration_type", 48),
                                        ("align_image", 27),
                                        ("bg_color", 49),
                                    ]
                                ],
                                {},
                            ),
                            51: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "Ready to secure your operations?",
                                    "required": True,
                                },
                            ),
                            52: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "Connect your first edge gateway in 24 hours. Activate your pilot program today.",
                                    "required": True,
                                },
                            ),
                            53: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Activate Pilot Program", "required": True},
                            ),
                            54: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "See Plans & Pricing", "required": False},
                            ),
                            55: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "/pricing/", "required": False},
                            ),
                            56: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 51),
                                        ("subtitle", 52),
                                        ("primary_cta_text", 53),
                                        ("primary_cta_url", 4),
                                        ("secondary_cta_text", 54),
                                        ("secondary_cta_url", 55),
                                    ]
                                ],
                                {},
                            ),
                            57: ("wagtail.blocks.RichTextBlock", (), {}),
                            58: ("wagtail.blocks.RawHTMLBlock", (), {}),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="NodeflowHomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "social_image",
                    models.ImageField(
                        blank=True,
                        help_text="The image to use in social sharing metadata.",
                        null=True,
                        upload_to="",
                    ),
                ),
                (
                    "hero_tagline",
                    models.CharField(
                        blank=True, default="Industrial Intelligence", max_length=255
                    ),
                ),
                (
                    "hero_title",
                    models.CharField(
                        blank=True,
                        default="Your Factory, Perfectly Synchronized.",
                        max_length=255,
                    ),
                ),
                (
                    "hero_subtitle",
                    models.TextField(
                        blank=True,
                        default="Connect industrial PLCs, meters, and sensors to a secure unified cloud plane. Harness AI-guided template registry, local edge network failover, and zero-downtime upgrades in 24 hours.",
                    ),
                ),
                (
                    "hero_cta_text",
                    models.CharField(
                        blank=True, default="Activate Cloud Access", max_length=100
                    ),
                ),
                (
                    "hero_cta_url",
                    models.CharField(
                        blank=True, default="/accounts/signup/", max_length=255
                    ),
                ),
                (
                    "hero_secondary_cta_text",
                    models.CharField(
                        blank=True, default="Explore Platform", max_length=100
                    ),
                ),
                (
                    "hero_secondary_cta_url",
                    models.CharField(blank=True, default="#features", max_length=255),
                ),
                (
                    "show_terminal_simulator",
                    models.BooleanField(
                        default=True,
                        help_text="Show the interactive terminal simulator on the right side of the hero.",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("trusted_by", 3),
                            ("feature_grid", 12),
                            ("ai_spotlight", 17),
                            ("final_cta", 24),
                            ("html", 25),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "Empowering Industry Leaders Across ASEAN",
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "Company Name"},
                            ),
                            2: ("wagtail.blocks.ListBlock", (1,), {}),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("tagline", 0), ("companies", 2)]],
                                {},
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Core Capabilities", "required": False},
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "Engineered for Extreme Operational Resilience.",
                                    "required": True,
                                },
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "fa-chart-line",
                                    "help_text": "FontAwesome class name",
                                    "required": True,
                                },
                            ),
                            7: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            8: ("wagtail.blocks.TextBlock", (), {"required": True}),
                            9: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("icon", 6),
                                        ("title", 7),
                                        ("description", 8),
                                        ("link_text", 9),
                                        ("link_url", 9),
                                    ]
                                ],
                                {},
                            ),
                            11: ("wagtail.blocks.ListBlock", (10,), {}),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [[("tagline", 4), ("title", 5), ("features", 11)]],
                                {},
                            ),
                            13: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Built-in Intelligence", "required": False},
                            ),
                            14: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "Stop searching for logs. Start asking questions.",
                                    "required": True,
                                },
                            ),
                            15: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "Show yesterday's efficiency trends for Factory Floor A.",
                                    "required": True,
                                },
                            ),
                            16: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Nodeflow AI", "required": False},
                            ),
                            17: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("tagline", 13),
                                        ("title", 14),
                                        ("body", 8),
                                        ("prompt_text", 15),
                                        ("response_tagline", 16),
                                        ("response_text", 8),
                                    ]
                                ],
                                {},
                            ),
                            18: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "Ready to secure your operations?",
                                    "required": True,
                                },
                            ),
                            19: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "Connect your first edge gateway in 24 hours. Activate your pilot program today.",
                                    "required": True,
                                },
                            ),
                            20: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Activate Pilot Program", "required": True},
                            ),
                            21: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "/accounts/signup/", "required": True},
                            ),
                            22: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "See Plans & Pricing", "required": False},
                            ),
                            23: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "/pricing/", "required": False},
                            ),
                            24: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 18),
                                        ("subtitle", 19),
                                        ("primary_cta_text", 20),
                                        ("primary_cta_url", 21),
                                        ("secondary_cta_text", 22),
                                        ("secondary_cta_url", 23),
                                    ]
                                ],
                                {},
                            ),
                            25: ("wagtail.blocks.RawHTMLBlock", (), {}),
                        },
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
