# Generated by Django 5.2 on 2026-04-09 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0003_team_billing_details_last_changed_team_customer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("manufacturer", models.CharField(blank=True, max_length=200)),
                ("model_number", models.CharField(blank=True, max_length=200)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("power_meter", "Power Meter"),
                            ("solar_inverter", "Solar Inverter"),
                            ("vfd", "Variable Frequency Drive"),
                            ("plc", "PLC"),
                            ("temp_sensor", "Temperature Sensor"),
                            ("chiller", "Chiller"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("modbus_tcp", "Modbus TCP"),
                            ("modbus_rtu", "Modbus RTU"),
                            ("opcua", "OPC-UA"),
                            ("mqtt", "MQTT"),
                            ("bacnet", "BACnet"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "register_map",
                    models.JSONField(
                        help_text="Definition of Modbus registers or OPC-UA nodes"
                    ),
                ),
                (
                    "default_polling_interval",
                    models.IntegerField(
                        default=5, help_text="Seconds between data reads"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("energy", "Energy Monitoring"),
                            ("cold_chain", "Cold Chain"),
                            ("factory", "Smart Factory"),
                        ],
                        default="energy",
                        max_length=20,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("timezone", models.CharField(default="Asia/Singapore", max_length=50)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teams.team",
                        verbose_name="Team",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Gateway",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                (
                    "access_token",
                    models.CharField(
                        help_text="MQTT authentication token",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="offline",
                        max_length=20,
                    ),
                ),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("firmware_version", models.CharField(blank=True, max_length=50)),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teams.team",
                        verbose_name="Team",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gateways",
                        to="devices.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("power_meter", "Power Meter"),
                            ("solar_inverter", "Solar Inverter"),
                            ("vfd", "Variable Frequency Drive"),
                            ("plc", "PLC"),
                            ("temp_sensor", "Temperature Sensor"),
                            ("chiller", "Chiller"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("modbus_tcp", "Modbus TCP"),
                            ("modbus_rtu", "Modbus RTU"),
                            ("opcua", "OPC-UA"),
                            ("mqtt", "MQTT"),
                            ("bacnet", "BACnet"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "energy_category",
                    models.CharField(
                        choices=[
                            ("generation", "Generation (Solar, Wind, etc.)"),
                            ("utility", "Utility (Main Grid)"),
                            ("consumption", "Consumption (Equipment, Building)"),
                            ("none", "None / Not Applicable"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "connection_config",
                    models.JSONField(
                        default=dict,
                        help_text="Modbus slave ID, IP address, port, etc.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("alarm", "Alarm"),
                        ],
                        default="offline",
                        max_length=20,
                    ),
                ),
                ("last_telemetry_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teams.team",
                        verbose_name="Team",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="devices.devicetemplate",
                    ),
                ),
                (
                    "gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="devices.gateway",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="devices.site",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
