# Generated by Django 5.2 on 2026-04-10 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gateway",
            name="capacity",
            field=models.PositiveIntegerField(
                default=8,
                help_text="Maximum number of devices this gateway can support",
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="gateway",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="devices.gateway",
            ),
        ),
    ]
