# Generated by Django 5.2 on 2026-04-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0002_gateway_capacity_alter_device_gateway"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicetemplate",
            name="alert_presets",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of default alert rules for this template",
            ),
        ),
        migrations.AddField(
            model_name="gateway",
            name="discovery_data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Most recent discovery report from the edge",
            ),
        ),
    ]
