# Generated by Django 5.2 on 2026-04-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0003_devicetemplate_alert_presets_gateway_discovery_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="port",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Physical port or address on the gateway",
                null=True,
            ),
        ),
    ]
