# Generated by Django 5.1.5 on 2026-04-17 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0004_device_port"),
        ("teams", "0005_alter_invitation_role_alter_membership_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="connection_config",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="device",
            name="port",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="devicetemplate",
            name="alert_presets",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="devicetemplate",
            name="default_polling_interval",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="devicetemplate",
            name="register_map",
            field=models.JSONField(
                help_text="Definition of registers. Keys can have 'writable': true."
            ),
        ),
        migrations.CreateModel(
            name="DeviceCommand",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("command_key", models.CharField(max_length=100)),
                ("value", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent to Gateway"),
                            ("executed", "Executed Successfully"),
                            ("failed", "Failed"),
                            ("timed_out", "Timed Out"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="The exact payload sent to the gateway",
                    ),
                ),
                ("response_payload", models.JSONField(blank=True, default=dict)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commands",
                        to="devices.device",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teams.team",
                        verbose_name="Team",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
