# Generated by Django 5.2 on 2026-04-21 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_alter_device_connection_config_alter_device_port_and_more'),
        ('teams', '0005_alter_invitation_role_alter_membership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='active_connectors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='gateway',
            name='client_cert_pem',
            field=models.TextField(blank=True, help_text='Client certificate PEM for mTLS'),
        ),
        migrations.AddField(
            model_name='gateway',
            name='client_key_pem',
            field=models.TextField(blank=True, help_text='Client private key PEM for mTLS'),
        ),
        migrations.AddField(
            model_name='gateway',
            name='connected_devices',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='gateway',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='mqtt_password',
            field=models.CharField(blank=True, help_text='Bcrypt hash of the MQTT password', max_length=255),
        ),
        migrations.AddField(
            model_name='gateway',
            name='mqtt_username',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='gateway',
            name='platform_info',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='gateway',
            name='python_version',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='gateway',
            name='tls_mode',
            field=models.CharField(choices=[('none', 'None'), ('one-way', 'One-Way TLS'), ('mutual', 'Mutual TLS')], default='one-way', max_length=10),
        ),
        migrations.AddField(
            model_name='gateway',
            name='uptime_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GatewayConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config_json', models.JSONField()),
                ('pushed_at', models.DateTimeField(auto_now_add=True)),
                ('request_id', models.UUIDField(unique=True)),
                ('action', models.CharField(default='full_update', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_history', to='devices.gateway')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'ordering': ['-pushed_at'],
            },
        ),
        migrations.CreateModel(
            name='RpcCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_id', models.UUIDField(unique=True)),
                ('method', models.CharField(max_length=50)),
                ('params', models.JSONField(default=dict)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('error', 'Error'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpc_commands', to='devices.gateway')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
