# Generated by Django 5.2 on 2026-04-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_gateway_active_connectors_gateway_client_cert_pem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='mqtt_username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
