# Generated by Django 5.2 on 2026-04-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_alter_gateway_mqtt_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='discovery_meta',
            field=models.JSONField(blank=True, default=dict, help_text='Raw discovery data from Edge (interface, slave_id, baud_rate, etc.)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='port',
            field=models.CharField(blank=True, help_text='Interface name or address (e.g., /dev/ttyUSB0, 192.168.1.100:502)', max_length=100, null=True),
        ),
    ]
