# Generated by Django 5.2 on 2026-06-05 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0008_device_port_to_charfield_add_discovery_meta"),
        ("teams", "0005_alter_invitation_role_alter_membership_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicetemplate",
            name="ai_confidence",
            field=models.FloatField(
                blank=True, help_text="AI confidence score 0.0-1.0", null=True
            ),
        ),
        migrations.AddField(
            model_name="devicetemplate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="devicetemplate",
            name="created_by_team",
            field=models.ForeignKey(
                blank=True,
                help_text="Team that originally created this template",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="devicetemplate",
            name="source",
            field=models.CharField(
                choices=[
                    ("curated", "Curated (Novena)"),
                    ("ai_generated", "AI Generated"),
                    ("user_created", "User Created"),
                ],
                default="curated",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="devicetemplate",
            name="source_url",
            field=models.URLField(
                blank=True,
                help_text="URL where the register map was found",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="devicetemplate",
            name="usage_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of devices using this template"
            ),
        ),
    ]
