# Generated by Django 5.2 on 2026-06-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0009_devicetemplate_ai_confidence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gateway",
            name="active_interface",
            field=models.CharField(blank=True, default="eth0", max_length=20),
        ),
        migrations.AddField(
            model_name="gateway",
            name="ethernet_status",
            field=models.CharField(blank=True, default="unknown", max_length=20),
        ),
        migrations.AddField(
            model_name="gateway",
            name="failover_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="gateway",
            name="fourg_status",
            field=models.CharField(blank=True, default="unknown", max_length=20),
        ),
        migrations.AddField(
            model_name="gateway",
            name="signal_strength",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gateway",
            name="wifi_status",
            field=models.CharField(blank=True, default="unknown", max_length=20),
        ),
    ]
