# Generated by Django 5.2 on 2026-06-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0010_gateway_active_interface_gateway_ethernet_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FirmwareRelease",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Version string, e.g. '1.1.0'",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("release_notes", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(
                        help_text="The firmware binary tarball (.tar.gz)",
                        upload_to="firmware/",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this release is available to gateways",
                    ),
                ),
                ("released_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-released_at"],
            },
        ),
    ]
