# Generated by Django 5.2 on 2026-06-27 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_firmwarerelease'),
        ('teams', '0005_alter_invitation_role_alter_membership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='lifecycle_status',
            field=models.CharField(choices=[('claimed', 'Claimed'), ('online', 'Online'), ('commissioning', 'Commissioning'), ('active', 'Active')], default='claimed', max_length=20),
        ),
        migrations.CreateModel(
            name='GatewayInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('unclaimed', 'Unclaimed'), ('claimed', 'Claimed'), ('retired', 'Retired')], default='unclaimed', max_length=20)),
                ('batch', models.CharField(blank=True, max_length=100)),
                ('manufactured_at', models.DateTimeField(auto_now_add=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('claimed_by_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_gateway_inventory', to='teams.team')),
                ('gateway', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_record', to='devices.gateway')),
            ],
            options={
                'verbose_name_plural': 'gateway inventory',
                'ordering': ['serial_number'],
            },
        ),
    ]
