# Generated by Codex on 2026-07-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0012_gateway_lifecycle_status_gatewayinventory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gateway",
            name="lifecycle_status",
            field=models.CharField(
                choices=[
                    ("claimed", "Claimed"),
                    ("bootstrap_seen", "Bootstrap Seen"),
                    ("activating", "Activating"),
                    ("online", "Online"),
                    ("commissioning", "Commissioning"),
                    ("active", "Active"),
                    ("release_pending", "Release Pending"),
                ],
                default="claimed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="gateway",
            name="mqtt_provisioning_status",
            field=models.CharField(default="not_started", max_length=20),
        ),
        migrations.AddField(
            model_name="gateway",
            name="mqtt_provisioning_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="gateway",
            name="mqtt_provisioned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gateway",
            name="credential_rotation_status",
            field=models.CharField(default="not_started", max_length=20),
        ),
        migrations.AddField(
            model_name="gateway",
            name="last_bootstrap_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gateway",
            name="mqtt_password",
            field=models.CharField(blank=True, help_text="Hashed operational MQTT password", max_length=255),
        ),
        migrations.AddField(
            model_name="gateway",
            name="buffered_event_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gateway",
            name="last_replay_status",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="gateway",
            name="replay_failure_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="gatewayinventory",
            name="status",
            field=models.CharField(
                choices=[
                    ("unclaimed", "Unclaimed"),
                    ("claimed", "Claimed"),
                    ("released", "Released"),
                    ("retired", "Retired"),
                ],
                default="unclaimed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="devicetemplate",
            name="discovery_hints",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="firmwarerelease",
            name="sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="firmwarerelease",
            name="size_bytes",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
