# Generated by Codex on 2026-07-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0013_gateway_self_serve_reclaim"),
    ]

    operations = [
        migrations.AddField(
            model_name="devicecommand",
            name="command_type",
            field=models.CharField(
                choices=[("read", "Read"), ("write", "Write")],
                default="write",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="devicecommand",
            name="rpc_command",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="device_command",
                to="devices.rpccommand",
            ),
        ),
        migrations.AlterField(
            model_name="devicecommand",
            name="value",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
