# Generated by Django 5.2 on 2026-07-22 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0017_gatewayactivation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gatewayactivation',
            new_name='devices_gat_gateway_235b19_idx',
            old_name='devices_gat_gateway_74a7a9_idx',
        ),
        migrations.RenameIndex(
            model_name='gatewayactivation',
            new_name='devices_gat_expires_3c2d1c_idx',
            old_name='devices_gat_expires_970405_idx',
        ),
    ]
