# Generated by Django 5.2 on 2026-07-25 16:23

from django.db import migrations, models


def mark_existing_templates_as_schema_v2(apps, schema_editor):
    DeviceTemplate = apps.get_model("devices", "DeviceTemplate")
    DeviceTemplate.objects.filter(datapoint_schema_version__lt=2).update(datapoint_schema_version=2)


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0025_guided_commissioning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetemplate',
            name='datapoint_schema_version',
            field=models.PositiveSmallIntegerField(default=2, help_text='Version of the normalized datapoint representation stored in register_map.'),
        ),
        migrations.RunPython(mark_existing_templates_as_schema_v2, migrations.RunPython.noop),
    ]
