# Generated by Django 5.1.5 on 2026-04-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_language_customuser_timezone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Format: +65XXXXXXXX for Singapore numbers.",
                max_length=20,
            ),
        ),
    ]
