# Generated by Django 5.2 on 2026-06-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="department",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="customuser",
            name="job_title",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
