# Generated by Django 5.2 on 2026-07-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_closed_at_customuser_closed_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='closed_reason',
            field=models.CharField(blank=True, db_default='', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='original_email_hash',
            field=models.CharField(blank=True, db_default='', default='', max_length=64),
        ),
    ]
