# Generated by Django 5.2 on 2026-06-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="preventiveschedule",
            name="is_usage_based",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="preventiveschedule",
            name="last_trigger_usage_value",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name="preventiveschedule",
            name="usage_telemetry_key",
            field=models.CharField(blank=True, default="run_hours", max_length=100),
        ),
        migrations.AddField(
            model_name="preventiveschedule",
            name="usage_threshold",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="preventiveschedule",
            name="interval",
            field=models.CharField(
                blank=True,
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                    ("yearly", "Yearly"),
                ],
                default="monthly",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="preventiveschedule",
            name="next_due_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
