# Generated by Django 5.2 on 2026-06-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0002_preventiveschedule_is_usage_based_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenanceticket",
            name="send_email_notification",
            field=models.BooleanField(
                default=True, verbose_name="Notify assignee via Email"
            ),
        ),
        migrations.AddField(
            model_name="maintenanceticket",
            name="send_whatsapp_notification",
            field=models.BooleanField(
                default=False, verbose_name="Notify assignee via WhatsApp"
            ),
        ),
    ]
