# Generated by Django 5.2 on 2026-06-20 05:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0003_maintenanceticket_send_email_notification_and_more"),
        ("teams", "0005_alter_invitation_role_alter_membership_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="preventiveschedule",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maintenance_schedules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="preventiveschedule",
            name="send_email_notification",
            field=models.BooleanField(
                default=True, verbose_name="Notify assignee via Email"
            ),
        ),
        migrations.AddField(
            model_name="preventiveschedule",
            name="send_whatsapp_notification",
            field=models.BooleanField(
                default=False, verbose_name="Notify assignee via WhatsApp"
            ),
        ),
        migrations.AddField(
            model_name="ticketcomment",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="Upload signed logsheets, checklist photos, or certificates (PDF, JPG, PNG up to 10MB)",
                null=True,
                upload_to="maintenance/attachments/",
            ),
        ),
        migrations.AddField(
            model_name="ticketcomment",
            name="guest_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name="SharedTicketLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Optional expiration date", null=True
                    ),
                ),
                (
                    "auto_revoke_on_resolve",
                    models.BooleanField(
                        default=True,
                        help_text="Deactivate this link automatically once the ticket is resolved",
                    ),
                ),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("last_viewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teams.team",
                        verbose_name="Team",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_links",
                        to="maintenance.maintenanceticket",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
