# Generated by Django 5.2 on 2026-07-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_preventiveschedule_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceticket',
            name='labor_minutes',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Actual hands-on labor recorded for this work item.'),
        ),
    ]
