# Generated by Django 5.1.5 on 2026-04-17 12:50

from django.db import migrations

def migrate_roles(apps, schema_editor):
    Membership = apps.get_model('teams', 'Membership')
    Invitation = apps.get_model('teams', 'Invitation')

    # Mapping: admin -> owner, member -> manager
    Membership.objects.filter(role='admin').update(role='owner')
    Membership.objects.filter(role='member').update(role='manager')

    Invitation.objects.filter(role='admin').update(role='owner')
    Invitation.objects.filter(role='member').update(role='manager')

def reverse_migrate_roles(apps, schema_editor):
    Membership = apps.get_model('teams', 'Membership')
    Invitation = apps.get_model('teams', 'Invitation')

    Membership.objects.filter(role='owner').update(role='admin')
    Membership.objects.filter(role='manager').update(role='member')
    Membership.objects.filter(role='operator').update(role='member')
    Membership.objects.filter(role='viewer').update(role='member')

    Invitation.objects.filter(role='owner').update(role='admin')
    Invitation.objects.filter(role='manager').update(role='member')
    Invitation.objects.filter(role='operator').update(role='member')
    Invitation.objects.filter(role='viewer').update(role='member')


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0003_team_billing_details_last_changed_team_customer_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_roles, reverse_migrate_roles),
    ]
