# Generated by Django 5.1.5 on 2026-04-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0004_migrate_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Administrator"),
                    ("manager", "Site Manager"),
                    ("operator", "Operator"),
                    ("viewer", "Viewer"),
                ],
                default="viewer",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Administrator"),
                    ("manager", "Site Manager"),
                    ("operator", "Operator"),
                    ("viewer", "Viewer"),
                ],
                max_length=100,
            ),
        ),
    ]
