# Generated by Django 5.2 on 2026-07-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0006_team_closure_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="closed_reason",
            field=models.CharField(blank=True, db_default="", default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="team",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("closed", "Closed")],
                db_default="active",
                default="active",
                max_length=20,
            ),
        ),
    ]
