# Generated by Django 5.2 on 2026-04-09 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelemetryData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("key", models.CharField(max_length=100)),
                ("value_numeric", models.FloatField(blank=True, null=True)),
                ("value_string", models.TextField(blank=True, null=True)),
                ("value_bool", models.BooleanField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Telemetry data",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "key", "timestamp"],
                        name="telemetry_t_device__595d97_idx",
                    )
                ],
            },
        ),
    ]
