# Generated by Django 5.2 on 2026-04-21 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_gateway_active_connectors_gateway_client_cert_pem_and_more'),
        ('telemetry', '0003_create_aggregates'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('level', models.CharField(max_length=20)),
                ('logger_name', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('module', models.CharField(blank=True, max_length=100)),
                ('line', models.IntegerField(blank=True, null=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='devices.gateway')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['gateway', 'timestamp'], name='telemetry_g_gateway_af8093_idx'), models.Index(fields=['gateway', 'level'], name='telemetry_g_gateway_3217d7_idx')],
            },
        ),
    ]
